server:
  port: 8088

spring:
  datasource:
    druid:
      password: kechen
      username: root
      url: jdbc:mysql://localhost:3306/online?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver